In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

**KNN Imputer**

Find Kmeans Neighbours

Find euclidean distance

Dist(x,y) = sqrt(weight * sq.distance from present coordinates

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
pd.read_csv('/kaggle/input/competitions/titanic/train.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df = pd.read_csv('/kaggle/input/competitions/titanic/train.csv', usecols = ['Age','Pclass','Fare','Survived'])

In [5]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [6]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [7]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [9]:
x_train.head()

     Pclass   Age     Fare
331       1  45.5  28.5000
733       2  23.0  13.0000
382       3  32.0   7.9250
704       3  26.0   7.8542
813       3   6.0  31.2750

In [10]:
knn = KNNImputer(n_neighbors = 3 , weights = 'distance')
x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [11]:
pd.DataFrame(x_train_trf, columns = x_train.columns)

     Pclass   Age      Fare
0       1.0  45.5   28.5000
1       2.0  23.0   13.0000
2       3.0  32.0    7.9250
3       3.0  26.0    7.8542
4       3.0   6.0   31.2750
..      ...   ...       ...
707     3.0  21.0    7.6500
708     1.0  38.0   31.0000
709     3.0  41.0   14.1083
710     1.0  14.0  120.0000
711     1.0  21.0   77.2875

[712 rows x 3 columns]

In [12]:
print("x_train_trf shape:", x_train_trf.shape)
print("y_train shape:", y_train.shape)

x_train_trf shape: (712, 3)
y_train shape: (712,)

In [13]:
lr = LogisticRegression()
lr.fit(x_train_trf, y_train)
y_pred = lr.predict(x_test_trf)
accuracy_score(y_test, y_pred)

0.7374301675977654

In [14]:
si = SimpleImputer()
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [15]:
lr = LogisticRegression()
lr.fit(x_train_trf2,y_train)
y_pred2 = lr.predict(x_test_trf2)